[
  {
    "test": "Server Connectivity",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F1816C080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:06.514499"
  },
  {
    "test": "Charger Logs",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/logs/kushagra01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F5EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:11.571134"
  },
  {
    "test": "ID Tag Management",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/idtags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F66F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:16.646096"
  },
  {
    "test": "Remote Operations",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/remote_start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F6D80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:21.714127"
  },
  {
    "test": "Configuration Management",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/get_configuration (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F7530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:26.756430"
  },
  {
    "test": "Cache and Reset",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/clear_cache (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184BE0C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:31.827533"
  },
  {
    "test": "Local List Management",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/get_local_list_version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F7800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:36.885498"
  },
  {
    "test": "TriggerMessage",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/trigger_message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F6DB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:41.948248"
  },
  {
    "test": "Availability Management",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/change_availability (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F6480>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:46.989764"
  },
  {
    "test": "Reservation Management",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/reserve_now (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F7E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:52.023517"
  },
  {
    "test": "Charging Profiles",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/set_charging_profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F185307D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:11:57.079716"
  },
  {
    "test": "Firmware and Diagnostics",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/update_firmware (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F7E30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:12:02.126835"
  },
  {
    "test": "Data Transfer",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/data_transfer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F63C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:12:07.167903"
  },
  {
    "test": "UnlockConnector",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/send/kushagra01/unlock_connector (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F7050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:12:12.208795"
  },
  {
    "test": "Log Filtering",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/logs/kushagra01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F184F7200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:12:17.243025"
  },
  {
    "test": "UI Features",
    "status": "FAIL",
    "details": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/config/ui-features (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028F18530860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
    "timestamp": "2025-06-19T16:12:22.280912"
  }
]